apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: podinfo
      namespace: info
    patch: |-
      - op: replace 
        path: /spec/minReplicas
        value: 3
      - op: replace 
        path: /spec/maxReplicas
        value: 6
