apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - ../base/nginx
patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: podinfo
    patch: |-
      - op: replace 
        path: /spec/minReplicas
        value: 3
